services:
  - type: worker
    name: transkrib-bot
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TRANSKRIB_API_URL
        value: https://transkrib-api.onrender.com
